import React from "react";
import SelectTestMetrics from "../RequestComponents/SelectTestMetrics";
import { QuestionMarkCircleIcon } from "@heroicons/react/24/outline";
import { useFormContext } from "react-hook-form";

/*

Linear SVR component for federated learning.

Schema of this component (model_info object generated by this component):

==================================================
sample model_info object:

  "model_info": {
    "C": 1.0,
    "epsilon": 0.1,
    "test_metrics": ["mse", "mae", "r2"]
  }

Parameters:
- C: Regularization parameter (float)
- epsilon: Epsilon-insensitive loss width
- test_metrics: Evaluation metrics for regression

Note: This component is restricted to LINEAR kernels only for federated learning compatibility.

==================================================

*/

const CustomSVR = () => {
  const { register, watch } = useFormContext();

  const defaultValues = {
    C: 1.0,
    epsilon: 0.1,
    kernel: "linear",
    gamma: "scale",
    degree: 3,
    coef0: 0,
  };

  const selectedKernel = watch("model_info.kernel", defaultValues.kernel);

  // start of the model_info object
  return (
    <div className="max-w-3xl mx-auto space-y-6">
      {/* Regularization Parameter (C) */}
      <div className="flex items-center border border-gray-300 rounded-md p-2">
        <span className="bg-gray-200 text-gray-700 px-3 py-2 rounded-l-md">
          C / Regularization
        </span>
        <input
          type="number"
          step="0.1"
          min="0.01"
          className="flex-1 p-2 border-0 focus:ring-0 focus:outline-none"
          placeholder="e.g. 1.0"
          defaultValue={defaultValues.C}
          {...register("model_info.C")}
        />
      </div>

      {/* Epsilon */}
      <div className="flex items-center border border-gray-300 rounded-md p-2">
        <span className="bg-gray-200 text-gray-700 px-3 py-2 rounded-l-md">
          Epsilon
        </span>
        <input
          type="number"
          step="0.01"
          min="0.0"
          className="flex-1 p-2 border-0 focus:ring-0 focus:outline-none"
          placeholder="e.g. 0.1"
          defaultValue={defaultValues.epsilon}
          {...register("model_info.epsilon")}
        />
      </div>

      {/* Kernel */}
      <div className="flex items-center border border-gray-300 rounded-md p-2">
        <span className="bg-gray-200 text-gray-700 px-3 py-2 rounded-l-md">
          Kernel
        </span>
        <select
          className="flex-1 p-2 border-0 focus:ring-0 focus:outline-none"
          defaultValue={defaultValues.kernel}
          {...register("model_info.kernel")}
        >
          <option value="linear">linear</option>
          <option value="rbf">rbf</option>
          <option value="poly">poly</option>
        </select>
      </div>

      {/* Gamma (for rbf/poly) */}
      {(selectedKernel === "rbf" || selectedKernel === "poly") && (
        <div className="flex items-center border border-gray-300 rounded-md p-2">
          <span className="bg-gray-200 text-gray-700 px-3 py-2 rounded-l-md">
            Gamma
          </span>
          <input
            type="text"
            className="flex-1 p-2 border-0 focus:ring-0 focus:outline-none"
            placeholder="e.g. scale, auto, or 0.1"
            defaultValue={defaultValues.gamma}
            {...register("model_info.gamma")}
          />
        </div>
      )}

      {/* Degree, Coef0 (for poly) */}
      {selectedKernel === "poly" && (
        <>
          <div className="flex items-center border border-gray-300 rounded-md p-2">
            <span className="bg-gray-200 text-gray-700 px-3 py-2 rounded-l-md">
              Degree
            </span>
            <input
              type="number"
              min="1"
              className="flex-1 p-2 border-0 focus:ring-0 focus:outline-none"
              placeholder="e.g. 3"
              defaultValue={defaultValues.degree}
              {...register("model_info.degree")}
            />
          </div>
          <div className="flex items-center border border-gray-300 rounded-md p-2">
            <span className="bg-gray-200 text-gray-700 px-3 py-2 rounded-l-md">
              Coef0
            </span>
            <input
              type="number"
              step="0.1"
              className="flex-1 p-2 border-0 focus:ring-0 focus:outline-none"
              placeholder="e.g. 0.0"
              defaultValue={defaultValues.coef0}
              {...register("model_info.coef0")}
            />
          </div>
        </>
      )}

      {/* Select Test Metrics */}
      <SelectTestMetrics register={register} />
    </div>
  );
};

export default CustomSVR;
