import React, { useEffect } from "react";
import SelectTestMetrics from "../RequestComponents/SelectTestMetrics";
import { useFormContext } from "react-hook-form";
import { HashtagIcon } from "@heroicons/react/24/outline";

/*
Schema of this component (model_info object generated by this component):

==================================================
sample model_info object:

  "model_info": {
    "n_neighbors": 5,
    "weights": "uniform",
    "metric": "minkowski",
    "test_metrics": ["accuracy", "f1_score"]
  }

Parameters:
- n_neighbors: Number of nearest neighbors to use
- weights: Weight function — "uniform" or "distance"
- metric: Distance metric — "minkowski", "euclidean", or "manhattan"
==================================================
*/

const KNNClassifier = () => {
  const { register, watch, setValue } = useFormContext();
  const defaultValues = {
    n_neighbors: 5,
    weights: "uniform",
    metric: "minkowski",
  };

  useEffect(() => {
    const currentModelInfo = watch("model_info") || {};
    if (!currentModelInfo.n_neighbors)
      setValue("model_info.n_neighbors", defaultValues.n_neighbors);
    if (!currentModelInfo.weights)
      setValue("model_info.weights", defaultValues.weights);
    if (!currentModelInfo.metric)
      setValue("model_info.metric", defaultValues.metric);
  }, [setValue, watch]);

  return (
    <div className="p-4 bg-white rounded-lg shadow-md">
      <p className="text-lg font-semibold mb-4">
        Configure the KNN Classifier Model Parameters:
      </p>

      {/* Number of Neighbors */}
      <div className="mb-4">
        <label
          className="flex items-center text-gray-700 font-medium mb-1"
          htmlFor="n_neighbors"
          title="Number of nearest neighbors to consider for classification"
        >
          <HashtagIcon className="h-5 w-5 mr-2 text-blue-500" />
          Number of Neighbors (k)
        </label>
        <input
          type="number"
          step="1"
          min="1"
          placeholder="e.g. 5"
          {...register("model_info.n_neighbors")}
          className="w-full p-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-400 focus:outline-none"
        />
      </div>

      {/* Weight Function */}
      <div className="mb-4">
        <label
          className="flex items-center text-gray-700 font-medium mb-1"
          htmlFor="weights"
          title="'uniform' weights all neighbors equally; 'distance' weights closer neighbors more"
        >
          <HashtagIcon className="h-5 w-5 mr-2 text-blue-500" />
          Weight Function
        </label>
        <select
          {...register("model_info.weights")}
          className="w-full p-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-400 focus:outline-none"
        >
          <option value="uniform">Uniform</option>
          <option value="distance">Distance</option>
        </select>
      </div>

      {/* Distance Metric */}
      <div className="mb-4">
        <label
          className="flex items-center text-gray-700 font-medium mb-1"
          htmlFor="metric"
          title="Distance metric used to compute nearest neighbors"
        >
          <HashtagIcon className="h-5 w-5 mr-2 text-blue-500" />
          Distance Metric
        </label>
        <select
          {...register("model_info.metric")}
          className="w-full p-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-400 focus:outline-none"
        >
          <option value="minkowski">Minkowski</option>
          <option value="euclidean">Euclidean</option>
          <option value="manhattan">Manhattan</option>
        </select>
      </div>

      {/* Select Test Metrics */}
      <SelectTestMetrics register={register} />
    </div>
  );
};

export default KNNClassifier;
