import React, { useEffect } from "react";
import SelectTestMetrics from "../RequestComponents/SelectTestMetrics";
import { useFormContext } from "react-hook-form";
import {
  AdjustmentsHorizontalIcon,
  HashtagIcon,
} from "@heroicons/react/24/outline";

/*
Schema of this component (model_info object generated by this component):

==================================================
sample model_info object:

  "model_info": {
    "alpha": 1.0,
    "lr": 0.01,
    "n_iters": 1000,
    "test_metrics": ["mse", "mae"]
  }

Parameters:
- alpha: L1 regularization strength
- lr: Learning rate (used by manual fallback)
- n_iters: Number of iterations
==================================================
*/

const LassoRegression = () => {
  const { register, watch, setValue } = useFormContext();
  const defaultValues = {
    alpha: 1.0,
    lr: 0.01,
    n_iters: 1000,
  };

  useEffect(() => {
    const currentModelInfo = watch("model_info") || {};
    if (!currentModelInfo.alpha) setValue("model_info.alpha", defaultValues.alpha);
    if (!currentModelInfo.lr) setValue("model_info.lr", defaultValues.lr);
    if (!currentModelInfo.n_iters) setValue("model_info.n_iters", defaultValues.n_iters);
  }, [setValue, watch]);

  return (
    <div className="p-4 bg-white rounded-lg shadow-md">
      <p className="text-lg font-semibold mb-4">
        Configure the Lasso Regression Model Parameters:
      </p>

      {/* Alpha (L1 Regularization) */}
      <div className="mb-4">
        <label
          className="flex items-center text-gray-700 font-medium mb-1"
          htmlFor="alpha"
          title="L1 regularization strength — higher values enforce stronger sparsity"
        >
          <AdjustmentsHorizontalIcon className="h-5 w-5 mr-2 text-blue-500" />
          Alpha (L1 Regularization)
        </label>
        <input
          type="number"
          step="0.01"
          min="0"
          placeholder="e.g. 1.0"
          {...register("model_info.alpha")}
          className="w-full p-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-400 focus:outline-none"
        />
      </div>

      {/* Learning Rate */}
      <div className="mb-4">
        <label
          className="flex items-center text-gray-700 font-medium mb-1"
          htmlFor="lr"
          title="Learning rate for the manual gradient-descent fallback"
        >
          <AdjustmentsHorizontalIcon className="h-5 w-5 mr-2 text-blue-500" />
          Learning Rate
        </label>
        <input
          type="number"
          step="0.001"
          placeholder="e.g. 0.01"
          {...register("model_info.lr")}
          className="w-full p-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-400 focus:outline-none"
        />
      </div>

      {/* Number of Iterations */}
      <div className="mb-4">
        <label
          className="flex items-center text-gray-700 font-medium mb-1"
          htmlFor="n_iters"
          title="Maximum number of iterations for training"
        >
          <HashtagIcon className="h-5 w-5 mr-2 text-blue-500" />
          Number of Iterations
        </label>
        <input
          type="number"
          placeholder="e.g. 1000"
          {...register("model_info.n_iters")}
          className="w-full p-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-400 focus:outline-none"
        />
      </div>

      {/* Select Test Metrics */}
      <SelectTestMetrics register={register} />
    </div>
  );
};

export default LassoRegression;
