version: "3.8"

services:
  frontend:
    container_name: "frontend"
    build:
      context: ./frontend
    ports:
      - "5174:5174"
    volumes:
      - ./frontend/app:/app
      - /app/node_modules

  backend:
    container_name: "backend"
    build:
      context: ./backend
    ports:
      - "9090:9090"
    volumes:
      - ./backend/app:/app
      - ${DB_VOLUME}:/db_volume
    env_file:
      - .env
    environment:
      - DB_PATH=/db_volume/database.db

    # later remove volumes and uncomment copy code in individual Dockerfile
