version: "3.8"

services:
  frontend:
    container_name: "frontend"
    build:
      context: ./frontend
    ports:
      - "5174:5174"

  backend:
    container_name: "backend"
    build:
      context: ./backend
    ports:
      - "9000:9000"

    