import React, { useState } from "react";
import SelectTestMetrics from "../RequestComponents/SelectTestMetrics";
import { QuestionMarkCircleIcon } from "@heroicons/react/24/outline";
import { useFormContext } from "react-hook-form";
/*

Linear SVM component for federated learning.

Schema of this component (model_info object generated by this component):

==================================================
sample model_info object:

  "model_info": {
    "C": 1.0,
    "max_iter": 1000,
    "lr": 0.01,
    "weights_shape": "(5, 10)",
    "is_binary": "true",
    "test_metrics": ["accuracy", "f1_score", "precision", "recall"]
  }

Parameters:
- C: Regularization parameter (float)
- max_iter: Maximum iterations
- lr: Learning rate (for manual training fallback)
- weights_shape: Weight matrix shape (optional)
- is_binary: Binary vs multi-class classification
- test_metrics: Evaluation metrics

Note: This component is restricted to LINEAR kernels only for simplicity and federated learning compatibility.

==================================================

*/

const CustomSVM = () => {
  const { register } = useFormContext();

  const defaultValues = {
    C: 1.0,
    max_iter: 1000,
    lr: 0.01,
    weights_shape: "(5, 10)",
    is_binary: "true",
  };

  // start of the model_info object
  return (
    <div className="max-w-3xl mx-auto space-y-6">
      {/* Regularization Parameter (C) */}
      <div className="flex items-center border border-gray-300 rounded-md p-2">
        <span className="bg-gray-200 text-gray-700 px-3 py-2 rounded-l-md">
          C / Regularization
        </span>
        <input
          type="number"
          step="0.1"
          min="0.01"
          className="flex-1 p-2 border-0 focus:ring-0 focus:outline-none"
          placeholder="e.g. 1.0"
          defaultValue={defaultValues.C}
          {...register("model_info.C")}
        />
      </div>

      {/* Max Iterations */}
      <div className="flex items-center border border-gray-300 rounded-md p-2">
        <span className="bg-gray-200 text-gray-700 px-3 py-2 rounded-l-md">
          Max Iterations
        </span>
        <input
          type="number"
          min="100"
          max="10000"
          className="flex-1 p-2 border-0 focus:ring-0 focus:outline-none"
          placeholder="e.g. 1000"
          defaultValue={defaultValues.max_iter}
          {...register("model_info.max_iter")}
        />
      </div>

      {/* Learning Rate (for manual training) */}
      <div className="flex items-center border border-gray-300 rounded-md p-2">
        <span className="bg-gray-200 text-gray-700 px-3 py-2 rounded-l-md">
          Learning Rate
        </span>
        <input
          type="number"
          step="0.001"
          min="0.001"
          max="1.0"
          className="flex-1 p-2 border-0 focus:ring-0 focus:outline-none"
          placeholder="e.g. 0.01"
          defaultValue={defaultValues.lr}
          {...register("model_info.lr")}
        />
      </div>

      {/* Weight Shape */}
      <div className="flex items-center border border-gray-300 rounded-md p-2">
        <span className="bg-gray-200 text-gray-700 px-3 py-2 rounded-l-md">
          Weight Shape
        </span>
        <input
          type="text"
          className="flex-1 p-2 border-0 focus:ring-0 focus:outline-none"
          placeholder="e.g. (5, 10)"
          defaultValue={defaultValues.weights_shape}
          {...register("model_info.weights_shape")}
        />
      </div>

      {/* Classification Type */}
      <div className="border border-gray-300 rounded-md p-4">
        <p className="font-medium text-gray-700 mb-3">Classification Type</p>
        <div className="flex space-x-6">
          <label className="flex items-center space-x-2 cursor-pointer">
            <input
              type="radio"
              name="classificationType"
              value="true"
              className="accent-blue-500"
              defaultChecked={defaultValues.is_binary === "true"}
              {...register("model_info.is_binary")}
            />
            <span>Binary Classification</span>
          </label>
          <label className="flex items-center space-x-2 cursor-pointer">
            <input
              type="radio"
              name="classificationType"
              value="false"
              className="accent-blue-500"
              defaultChecked={defaultValues.is_binary === "false"}
              {...register("model_info.is_binary")}
            />
            <span>Multi-class Classification</span>
          </label>
        </div>
      </div>

      {/* Select Test Metrics */}
      <SelectTestMetrics register={register} />
    </div>
  );
};

export default CustomSVM;
