import React from "react";
import SelectTestMetrics from "../RequestComponents/SelectTestMetrics";
import { QuestionMarkCircleIcon } from "@heroicons/react/24/outline";
import { useFormContext } from "react-hook-form";

/*

Linear SVR component for federated learning.

Schema of this component (model_info object generated by this component):

==================================================
sample model_info object:

  "model_info": {
    "C": 1.0,
    "epsilon": 0.1,
    "test_metrics": ["mse", "mae", "r2"]
  }

Parameters:
- C: Regularization parameter (float)
- epsilon: Epsilon-insensitive loss width
- test_metrics: Evaluation metrics for regression

Note: This component is restricted to LINEAR kernels only for federated learning compatibility.

==================================================

*/

const CustomSVR = () => {
  const { register } = useFormContext();

  const defaultValues = {
    C: 1.0,
    epsilon: 0.1,
  };

  // start of the model_info object
  return (
    <div className="max-w-3xl mx-auto space-y-6">
      {/* Regularization Parameter (C) */}
      <div className="flex items-center border border-gray-300 rounded-md p-2">
        <span className="bg-gray-200 text-gray-700 px-3 py-2 rounded-l-md">
          C / Regularization
        </span>
        <input
          type="number"
          step="0.1"
          min="0.01"
          className="flex-1 p-2 border-0 focus:ring-0 focus:outline-none"
          placeholder="e.g. 1.0"
          defaultValue={defaultValues.C}
          {...register("model_info.C")}
        />
      </div>

      {/* Kernel Info */}
      <div className="border border-gray-300 rounded-md p-4 bg-blue-50">
        <div className="flex items-center space-x-2">
          <QuestionMarkCircleIcon className="h-5 w-5 text-blue-500" />
          <p className="font-medium text-gray-700">Linear Kernel Only</p>
        </div>
        <p className="text-sm text-gray-600 mt-2">
          This SVR implementation uses a linear kernel for federated learning
          compatibility. Linear SVR allows parameter sharing across clients.
        </p>
      </div>

      {/* Epsilon */}
      <div className="flex items-center border border-gray-300 rounded-md p-2">
        <span className="bg-gray-200 text-gray-700 px-3 py-2 rounded-l-md">
          Epsilon
        </span>
        <input
          type="number"
          step="0.01"
          min="0.0"
          className="flex-1 p-2 border-0 focus:ring-0 focus:outline-none"
          placeholder="e.g. 0.1"
          defaultValue={defaultValues.epsilon}
          {...register("model_info.epsilon")}
        />
      </div>

      {/* Select Test Metrics */}
      <SelectTestMetrics register={register} />
    </div>
  );
};

export default CustomSVR;
